# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EM(object):
    def setupUi(self, EM):
        EM.setObjectName("EM")
        EM.resize(1490, 1074)
        self.RAM_view = QtWidgets.QTableWidget(parent=EM)
        self.RAM_view.setGeometry(QtCore.QRect(450, 90, 251, 771))
        self.RAM_view.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.RAM_view.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.AnyKeyPressed|QtWidgets.QAbstractItemView.EditTrigger.DoubleClicked|QtWidgets.QAbstractItemView.EditTrigger.EditKeyPressed|QtWidgets.QAbstractItemView.EditTrigger.SelectedClicked)
        self.RAM_view.setAlternatingRowColors(True)
        self.RAM_view.setShowGrid(True)
        self.RAM_view.setGridStyle(QtCore.Qt.PenStyle.SolidLine)
        self.RAM_view.setCornerButtonEnabled(False)
        self.RAM_view.setRowCount(1000)
        self.RAM_view.setObjectName("RAM_view")
        self.RAM_view.setColumnCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.RAM_view.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.RAM_view.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.RAM_view.setItem(1, 0, item)
        self.RAM_view.horizontalHeader().setDefaultSectionSize(200)
        self.Code_view = QtWidgets.QTextBrowser(parent=EM)
        self.Code_view.setGeometry(QtCore.QRect(140, 90, 256, 771))
        self.Code_view.setReadOnly(False)
        self.Code_view.setObjectName("Code_view")
        self.tableWidget = QtWidgets.QTableWidget(parent=EM)
        self.tableWidget.setGeometry(QtCore.QRect(770, 160, 241, 711))
        self.tableWidget.setRowCount(100)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=EM)
        self.plainTextEdit.setGeometry(QtCore.QRect(1060, 540, 361, 261))
        self.plainTextEdit.setObjectName("plainTextEdit")

        self.retranslateUi(EM)
        QtCore.QMetaObject.connectSlotsByName(EM)

    def retranslateUi(self, EM):
        _translate = QtCore.QCoreApplication.translate
        EM.setWindowTitle(_translate("EM", "Dialog"))
        self.RAM_view.setSortingEnabled(False)
        item = self.RAM_view.horizontalHeaderItem(0)
        item.setText(_translate("EM", "RAM"))
        __sortingEnabled = self.RAM_view.isSortingEnabled()
        self.RAM_view.setSortingEnabled(False)
        item = self.RAM_view.item(0, 0)
        item.setText(_translate("EM", "11111111111111111111111"))
        item = self.RAM_view.item(1, 0)
        item.setText(_translate("EM", "1111111111"))
        self.RAM_view.setSortingEnabled(__sortingEnabled)
        self.Code_view.setPlaceholderText(_translate("EM", "test"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("EM", "New Column"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EM = QtWidgets.QDialog()
    ui = Ui_EM()
    ui.setupUi(EM)
    EM.show()
    sys.exit(app.exec())
